#!/bin/bash
# This is a modified version of Alexander Keller's <github@nycroth.com>
# wifi i3blocks blocklet with a more universal interface search and using
# NetworkManager for quality and ssid definition.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE=$(ip link | tr ' ' '\n' | tr ':' '\n' | grep wl)

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

# Using nm instead of /proc/net/wireless, which is not present in my systems
QUALITY=$(nmcli d wifi | egrep '[*]' | tr -s ' ' | cut -d ' ' -f7)
SSID=$(nmcli d wifi | egrep '[*]' | tr -s ' ' | cut -d ' ' -f2)

#------------------------------------------------------------------------

echo "$QUALITY" "$SSID" # full text
echo "$QUALITY" "$SSID" # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    echo "#657b83"
elif [[ $QUALITY -ge 60 ]]; then
    echo "#93a1a1"
elif [[ $QUALITY -ge 40 ]]; then
    echo "#b58900"
else
    echo "#dc322f"
fi
