-- Import Lua modules

require("packer_init")
require("core/keymaps")
require("core/options")
require("plugins/alpha-nvim")
require("plugins/auto-session")
require("plugins/github-nvim-theme")
require("plugins/lualine")
require("plugins/null-ls")
require("plugins/nvim-cmp")
require("plugins/nvim-lastplace")
require("plugins/nvim-lspconfig")
require("plugins/nvim-neoclip")
require("plugins/nvim-tree")
require("plugins/nvim-treesitter")
require("plugins/surround")
require("plugins/telescope")
require("plugins/toggleterm")
require("plugins/trouble")
